// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSqkHr8f4hh6pIhSOWa1GY1H9sfzsX6_Q',
    appId: '1:618927035684:web:fbb6ea4ff23caeaedf0fb1',
    messagingSenderId: '618927035684',
    projectId: 'readit-d09b3',
    authDomain: 'readit-d09b3.firebaseapp.com',
    storageBucket: 'readit-d09b3.appspot.com',
    measurementId: 'G-1WMCXX434Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCWfcPLbml_Ae-fL6gNToe6fbcl55Iv1k',
    appId: '1:618927035684:android:0ebeec6f18225ba6df0fb1',
    messagingSenderId: '618927035684',
    projectId: 'readit-d09b3',
    storageBucket: 'readit-d09b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7tbmLbwOrY4wF1DI0OB9DcekPcL8aSS8',
    appId: '1:618927035684:ios:c2976ff6b3996896df0fb1',
    messagingSenderId: '618927035684',
    projectId: 'readit-d09b3',
    storageBucket: 'readit-d09b3.appspot.com',
    iosBundleId: 'com.example.knowledgeWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7tbmLbwOrY4wF1DI0OB9DcekPcL8aSS8',
    appId: '1:618927035684:ios:c58b1c5c029ff016df0fb1',
    messagingSenderId: '618927035684',
    projectId: 'readit-d09b3',
    storageBucket: 'readit-d09b3.appspot.com',
    iosBundleId: 'com.example.knowledgeWorld.RunnerTests',
  );
}
